package PSM_interface;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PSM - Professor Schedule Manager
//  @ File Name : 
//  @ Date : 03/16/2008
//  @ Author : 
//
//
import PSM_logic.AppController;

public class InterfaceController {
    
    public Messages msg = new Messages();
    public LoginForm log = new LoginForm();
    public ScheduleForm sched = new ScheduleForm();
    public PrefilledScheduleForm edSched = new PrefilledScheduleForm();
    public MainMenu mm = new MainMenu();
    public LogOutConfirm logout = new LogOutConfirm();
    public CourseSelect cs;
    private AppController appController;
    
    public InterfaceController(AppController app)
    {
       this.appController = app;
    }
    
    public void passwordLock()
    {
        msg.lockedOut();
    }
    public void Initiate_Logout() 
    {
         msg.logoutConfirmation();
     
    }

    public void Initiate_IncorrectLogin()
    {       
        msg.incorrectLogin();
    }
    
    public void Initiate_Schedule_Form() 
    {
       
       sched.launchInitial();
    }

    public void Pre_Filled_Form(int courseID, String courseSubj, String courseName, String semester,
            String startDate, String endDate, String startMon, String endMon,
            String startTue, String endTue, String startWed, String endWed, String startThu, String endThu, 
            String startFri, String endFri, String startSat, String endSat) 
    {

    
        
         edSched.launchEdit(courseID, courseSubj, courseName, semester,
            startDate, endDate, startMon, endMon, startTue, endTue, 
            startWed, endWed, startThu, endThu, startFri, endFri, startSat, endSat);
    }
    
    public void Course_Select_Form(){
    	String ans = appController.fetchCourses();
        cs = new CourseSelect(ans);
        cs.launchCourse(ans);
    }
    public void Initiate_Login_Form() {

        log.launchForm();

    }

    public void Initiate_MainMenu() {
        mm.launchForm();

    }
}
